# Pack legs — Robbie's real route
LEGS = [
 dict(id="prep",   name="Before you go",      dates="Nov",             where="Home",            bags="L1 L2 CB BP SL", note="Everything assembled. The only leg where forgetting something is fixable."),
 dict(id="out",    name="Outbound long-haul", dates="19–20 Nov",       where="LGW→DOH→PER",     bags="L1 L2 CB BP SL", note="QR330 08:40 from Gatwick, QR900 out of Doha. ~26 hrs door to door. Qsuite, so pyjamas and bedding are provided — the sling is your seat-side kit."),
 dict(id="perth",  name="Perth — the long stay", dates="20 Nov–18 Dec", where="The Sebel West Perth", bags="L1 L2 CB BP SL", note="Four weeks. Working. Self-service laundry, so wash weekly and live out of the cases. Peak summer — 30–40°C."),
 dict(id="perth2", name="Perth — interim",     dates="18–29 Dec",       where="Not booked",      bags="L1 L2 CB BP SL", note="11 nights still unbooked. Same kit as the Sebel stay."),
 dict(id="scar",   name="Scarborough — Christmas", dates="29 Dec–7 Jan", where="Scarborough house", bags="L1 L2 CB BP SL", note="Christmas and New Year with everyone. Hire car from the 29th. Beach Christmas, but one smart evening."),
 dict(id="jet",    name="Jetstar to Phuket",   dates="7 Jan",           where="PER→HKT, JQ71",   bags="BP SL", note="07:25 departure. 40 kg checked prepaid, GBP 72.27 — that is the whole allowance, as the Starter fare includes none. Both cases and the cabin bag go in the hold against it. Backpack and sling are your only cabin items: two items, 7 kg combined, weighed at the gate, AUD 110 if you are over."),
 dict(id="phu",    name="Phuket",              dates="7–10 Jan",        where="Courtyard by Marriott Phuket Town", bags="L1 L2 CB BP SL", note="Three nights with everything still in tow. The last leg where you have the cases open."),
 dict(id="repack", name="THE REPACK — Phuket",   dates="10 Jan, morning",  where="Courtyard, before TG206", bags="L1 L2 CB BP SL", note="Do this here, with space and time, not at an airport. Everything you need for the next 13 days goes into the cabin bag, backpack and sling. Everything else goes into the two cases and gets locked. Both cases are checked on TG206 — 2 bags at 23 kg each, paid. Watch the cabin bag: Thai economy is officially one piece at 7 kg, and you will be carrying three. Keep it near 7 kg and wear the walking shoes. TG206 departs 11:50 — start after breakfast."),
 dict(id="drop",   name="Land and dump",       dates="10 Jan, 13:20",   where="Suvarnabhumi",    bags="CB BP SL", note="Booked and paid: Smilelugg, ref 14XIWBX4, two suitcases, 10–23 Jan, GBP 90.26. B Floor — the Airport Rail Link level. From the SA City Line station entrance walk ~50 m past the ticket kiosk to the Smilelugg counter. Straight off TG206, both cases in, photograph the receipt. Your taxi waits 45 min after landing, so there is time — but go directly."),
 dict(id="bkk1",   name="Bangkok",             dates="10–13 Jan",       where="Theatre Residence", bags="CB BP SL", note="Cabin bag only from here. Smart dress nights — Blue Elephant and the rooftops enforce long trousers and closed shoes, so that kit has to be in the cabin bag, not the cases."),
 dict(id="sam",    name="Koh Samui",           dates="13–17 Jan",       where="Hansar Samui Resort", bags="CB BP SL", note="Beach and resort. Light kit from here on."),
 dict(id="kha",    name="Khao Sok",            dates="17–19 Jan",       where="500 Rai Floating Resort", bags="CB BP SL", note="06:00 ferry from Lipa Noi, 2h15 by road, then in by boat. Floating raft house — limited power, properly dark, everything stays damp. Check-out 09:30 on the 19th."),
 dict(id="kra",    name="Ao Nang, Krabi",      dates="19–23 Jan",       where="Krabi La Playa Resort", bags="CB BP SL", note="Longtails to the beaches soak everything. Free cancellation ended 4 Jan — already paid."),
 dict(id="ret",    name="Collect and fly home", dates="23–24 Jan",      where="KBV→BKK→DOH→LHR", bags="L1 L2 CB BP SL", note="TG246 lands 14:10, QR835 departs 18:55 — 4h45 to clear arrivals, collect both cases from Smilelugg on B Floor (ref 14XIWBX4) and re-check. The counter is landside, so you have to come out first. Lands Heathrow 06:35 on the 24th, in January — have something warm reachable."),
]
