# Pack legs — Robbie's real route
LEGS = [
 dict(id="prep",   name="Before you go",      dates="Nov",             where="Home",            bags="L1 L2 CB BP SL", note="Everything assembled. The only leg where forgetting something is fixable."),
 dict(id="out",    name="Outbound long-haul", dates="19–20 Nov",       where="LGW→DOH→PER",     bags="L1 L2 CB BP SL",
      note="QR330 08:40 from Gatwick, QR900 out of Doha at 02:40, into Perth 18:45 on the 20th. About 26 hrs door to door with an 8h25 layover. Qsuite, so pyjamas and bedding are provided. Qatar Business gives you two cabin pieces at 15 kg plus a personal item, so the sling, backpack and cabin bag all travel with you — the cabin bag is your lost-luggage insurance.",
      plan=dict(
        worn=[
          dict(n="Hoodie and tracksuit bottoms", note="Your flight comfort set."),
          dict(n="Nice trainers", note="Wear the bulkiest footwear rather than packing it."),
        ],
        SL=[
          dict(n="Wallet and cards"), dict(n="Passport holder"), dict(n="Cash"),
          dict(n="AirPods Pro"), dict(n="Fold-up 3-in-1 charger"), dict(n="Extendable USB-C cable"),
          dict(n="Earplugs"), dict(n="Eye mask"), dict(n="Mouth tape"),
          dict(n="Phone"),
          dict(n="Mini charger brick", note="Cabin only, never checked."),
          dict(n="Prescription medication", add=True, note="Has to be hand luggage, in original packaging. Not in a hold bag."),
          dict(n="Clear 1L liquids bag", add=True, note="Travel suncream, sanitiser, lip balm. Needed at Gatwick and again at Doha."),
          dict(n="Australian ETA + insurance details", add=True, note="The airline checks the ETA at Gatwick."),
        ],
        BP=[
          dict(n="iPad Air", note="The main one — not the one being handed over in Phuket."),
          dict(n="USB-C dongle"), dict(n="HDMI cable"), dict(n="Compression socks"), dict(n="Larq bottle"),
          dict(n="Sony over-ear headphones", note="The flight you bought them for."),
          dict(n="Travel adapter", add=True, note="Perth is Type I. Doha is Type G like the UK, so the layover is fine, but you want this reachable on landing."),
        ],
        CB=[
          dict(n="2 boxers"), dict(n="2 socks"), dict(n="2 T-shirts"),
          dict(n="1 gym shirt"), dict(n="1 gym shorts"), dict(n="1 gym socks"),
          dict(n="Running shoes"), dict(n="1 swim shorts"), dict(n="MacBook Air"),
          dict(n="Mini washbag", note="Toothbrush, travel face wash, roll-on deodorant, aftershave atomiser. Covers the 26 hours and the Doha spa at 23:30."),
          dict(n="Windbreaker", add=True, note="Not worn, so it needs a home. Perth at 18:45 in November is warm — you do not actually need this again until Heathrow on 24 January, so a suitcase would do just as well."),
        ],
      )),
 dict(id="perth",  name="Perth — the long stay", dates="20 Nov–18 Dec", where="The Sebel West Perth", bags="L1 L2 CB BP SL", note="Four weeks. Working. Self-service laundry, so wash weekly and live out of the cases. Peak summer — 30–40°C."),
 dict(id="perth2", name="Perth — interim",     dates="18–29 Dec",       where="Not booked",      bags="L1 L2 CB BP SL", note="11 nights still unbooked. Same kit as the Sebel stay."),
 dict(id="scar",   name="Scarborough — Christmas", dates="29 Dec–7 Jan", where="Scarborough house", bags="L1 L2 CB BP SL", note="Christmas and New Year with everyone. Hire car from the 29th. Beach Christmas, but one smart evening."),
 dict(id="jet",    name="Jetstar to Phuket",   dates="7 Jan",           where="PER→HKT, JQ71",   bags="BP SL", note="07:25 departure. 40 kg checked prepaid, GBP 72.27 — that is the whole allowance, as the Starter fare includes none. Both cases and the cabin bag go in the hold against it. Backpack and sling are your only cabin items: two items, 7 kg combined, weighed at the gate, AUD 110 if you are over."),
 dict(id="phu",    name="Phuket",              dates="7–10 Jan",        where="Courtyard by Marriott Phuket Town", bags="L1 L2 CB BP SL", note="Three nights with everything still in tow. The last leg where you have the cases open."),
 dict(id="repack", name="THE REPACK — Phuket",   dates="10 Jan, morning",  where="Courtyard, before TG206", bags="L1 L2 CB BP SL", note="Do this here, with space and time, not at an airport. Everything you need for the next 13 days goes into the cabin bag, backpack and sling. Everything else goes into the two cases and gets locked. Both cases are checked on TG206 — 2 bags at 23 kg each, paid. Watch the cabin bag: Thai economy is officially one piece at 7 kg, and you will be carrying three. Keep it near 7 kg and wear the walking shoes. TG206 departs 11:50 — start after breakfast."),
 dict(id="drop",   name="Land and dump",       dates="10 Jan, 13:20",   where="Suvarnabhumi",    bags="CB BP SL", note="Booked and paid: Smilelugg, ref 14XIWBX4, two suitcases, 10–23 Jan, GBP 90.26. B Floor — the Airport Rail Link level. From the SA City Line station entrance walk ~50 m past the ticket kiosk to the Smilelugg counter. Straight off TG206, both cases in, photograph the receipt. Your taxi waits 45 min after landing, so there is time — but go directly."),
 dict(id="bkk1",   name="Bangkok",             dates="10–13 Jan",       where="Theatre Residence", bags="CB BP SL", note="Cabin bag only from here. Smart dress nights — Blue Elephant and the rooftops enforce long trousers and closed shoes, so that kit has to be in the cabin bag, not the cases."),
 dict(id="sam",    name="Koh Samui",           dates="13–17 Jan",       where="Hansar Samui Resort", bags="CB BP SL", note="Beach and resort. Light kit from here on."),
 dict(id="kha",    name="Khao Sok",            dates="17–19 Jan",       where="500 Rai Floating Resort", bags="CB BP SL", note="06:00 ferry from Lipa Noi, 2h15 by road, then in by boat. Floating raft house — limited power, properly dark, everything stays damp. Check-out 09:30 on the 19th."),
 dict(id="kra",    name="Ao Nang, Krabi",      dates="19–23 Jan",       where="Krabi La Playa Resort", bags="CB BP SL", note="Longtails to the beaches soak everything. Free cancellation ended 4 Jan — already paid."),
 dict(id="ret",    name="Collect and fly home", dates="23–24 Jan",      where="KBV→BKK→DOH→LHR", bags="L1 L2 CB BP SL", note="TG246 lands 14:10, QR835 departs 18:55 — 4h45 to clear arrivals, collect both cases from Smilelugg on B Floor (ref 14XIWBX4) and re-check. The counter is landside, so you have to come out first. Lands Heathrow 06:35 on the 24th, in January — have something warm reachable."),
]
